export const products = [
    {
    id:1,
    image:'category-2.png',
    name:'hand tool kit',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:2,
    image:'category-2.png',
    name:'hand tool kit',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:3,
    image:'category-2.png',
    name:'hand tool kit',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:4,
    image:'category-2.png',
    name:'hand tool kit',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:5,
    image:'category-2.png',
    name:'hand tool kit',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:6,
    image:'category-2.png',
    name:'hand tool kit',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:7,
    image:'category-2.png',
    name:'hand tool kit 7',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
]
export const bestproducts = [
    {
    id:1,
    image:'category-2.png',
    name:'hand tool kit',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:2,
    image:'category-2.png',
    name:'hand tool kit',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:3,
    image:'category-2.png',
    name:'hand tool kit',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:4,
    image:'category-2.png',
    name:'hand tool kit',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:5,
    image:'category-2.png',
    name:'hand tool kit',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:6,
    image:'category-2.png',
    name:'hand tool kit',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
]
export const ptProducts = [
    {
    id:8,
    image:'category-2.png',
    name:'hand kit pt',
    reviews:5,
    price:12.24,
    // previousPrice:244.42,
    },
    {
    id:9,
    image:'category-2.png',
    name:'kit tool pt',
    reviews:5,
    price:149.24,
    // previousPrice:244.42,
    },
    {
    id:10,
    image:'category-2.png',
    name:'bandage kit pt',
    reviews:5,
    price:10.24,
    previousPrice:14.42,
    },
    {
    id:11,
    image:'category-2.png',
    name:'hand tool kit pt',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:12,
    image:'category-2.png',
    name:'hand tool kit pt',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:13,
    image:'category-2.png',
    name:'hand tool kit pt',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:14,
    image:'category-2.png',
    name:'hand tool kit 7 pt',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
]
export const htProducts = [
    {
    id:8,
    image:'category-2.png',
    name:'hand kit ht',
    reviews:5,
    price:12.24,
    // previousPrice:244.42,
    },
    {
    id:9,
    image:'category-2.png',
    name:'kit tool ht',
    reviews:5,
    price:149.24,
    // previousPrice:244.42,
    },
    {
    id:10,
    image:'category-2.png',
    name:'bandage kit ht',
    reviews:5,
    price:10.24,
    previousPrice:14.42,
    },
    {
    id:11,
    image:'category-2.png',
    name:'hand tool kit ht',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:12,
    image:'category-2.png',
    name:'hand tool kit ht',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:13,
    image:'category-2.png',
    name:'hand tool kit ht',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:14,
    image:'category-2.png',
    name:'hand tool kit 7 ht',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
]
export const plumbProducts = [
    {
    id:8,
    image:'category-2.png',
    name:'hand kit plumb',
    reviews:5,
    price:12.24,
    // previousPrice:244.42,
    },
    {
    id:9,
    image:'category-2.png',
    name:'kit tool plumb',
    reviews:5,
    price:149.24,
    // previousPrice:244.42,
    },
    {
    id:10,
    image:'category-2.png',
    name:'bandage kit plumb',
    reviews:5,
    price:10.24,
    previousPrice:14.42,
    },
    {
    id:11,
    image:'category-2.png',
    name:'hand tool kit plumb',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:12,
    image:'category-2.png',
    name:'hand tool kit plumb',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:13,
    image:'category-2.png',
    name:'hand tool kit plumb',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
    {
    id:14,
    image:'category-2.png',
    name:'hand tool kit 7 plumb',
    reviews:5,
    price:149.24,
    previousPrice:244.42,
    },
]